{{- if and (not .Values.mongoSecret.enabled) (or .Values.env.MONGO_URI .Values.env.NODE_ID) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pritunl-zero.fullname" . }}-config
  labels:
    {{- include "pritunl-zero.labels" . | nindent 4 }}
type: Opaque
stringData:
  pritunl-zero.json: |
    {
      "mongo_uri": {{ if .Values.env.MONGO_URI }}{{ .Values.env.MONGO_URI | quote }}{{ else }}""{{ end }},
      "node_id": {{ if .Values.env.NODE_ID }}{{ .Values.env.NODE_ID | quote }}{{ else }}""{{ end }}
    }
{{- end }}


