apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pritunl-zero.fullname" . }}
  labels:
    {{- include "pritunl-zero.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "pritunl-zero.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "pritunl-zero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pritunl-zero.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pritunl-zero.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if and .Values.mongoSecret.enabled .Values.mongoSecret.name }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoSecret.name }}
                  key: {{ .Values.mongoSecret.key }}
            {{- else if .Values.env.MONGO_URI }}
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
            {{- end }}
            {{- if .Values.env.NODE_ID }}
            - name: NODE_ID
              value: {{ .Values.env.NODE_ID | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            {{- if and (ne $key "MONGO_URI") (ne $key "NODE_ID") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /etc
            {{- end }}
            {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              mountPath: /tmp
            - name: varlog
              mountPath: /var/log
            {{- end }}
            {{- if .Values.caCertsSidecar.enabled }}
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: etc-ca-certificates
              mountPath: /etc/ca-certificates
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.caCertsSidecar.enabled }}
        - name: ca-certs-updater
          image: {{ .Values.caCertsSidecar.image.repository }}:{{ .Values.caCertsSidecar.image.tag }}
          imagePullPolicy: {{ .Values.caCertsSidecar.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache ca-certificates >/dev/null 2>&1 || true
              while true; do
                if [ -d "/usr/local/share/ca-certificates" ] && [ "$(ls -A /usr/local/share/ca-certificates 2>/dev/null)" ]; then
                  update-ca-certificates 2>/dev/null || true
                  cp -f /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt.updated 2>/dev/null || true
                  cp -f /etc/ssl/certs/ca-certificates.crt.updated /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true
                fi
                sleep {{ .Values.caCertsSidecar.updateInterval }}
              done
          volumeMounts:
            - name: ca-certs
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: etc-ca-certificates
              mountPath: /etc/ca-certificates
          {{- with .Values.caCertsSidecar.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - DAC_OVERRIDE
        {{- end }}
      volumes:
        {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmp
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        {{- end }}
        {{- if .Values.caCertsSidecar.enabled }}
        - name: ca-certs
          {{- if .Values.caCertsSidecar.configMap }}
          configMap:
            name: {{ .Values.caCertsSidecar.configMap }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: etc-ssl-certs
          emptyDir: {}
        - name: etc-ca-certificates
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}

