apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pritunl-zero.fullname" . }}
  labels:
    {{- include "pritunl-zero.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "pritunl-zero.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "pritunl-zero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pritunl-zero.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pritunl-zero.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if and .Values.mongoSecret.enabled .Values.mongoSecret.name }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoSecret.name }}
                  key: {{ .Values.mongoSecret.key }}
            {{- else if .Values.env.MONGO_URI }}
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
            {{- end }}
            {{- if .Values.env.NODE_ID }}
            - name: NODE_ID
              value: {{ .Values.env.NODE_ID | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            {{- if and (ne $key "MONGO_URI") (ne $key "NODE_ID") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /etc
            {{- end }}
            {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              mountPath: /tmp
            - name: varlog
              mountPath: /var/log
            {{- end }}
            {{- if .Values.caCertsSidecar.enabled }}
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: etc-ca-certificates
              mountPath: /etc/ca-certificates
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if .Values.caCertsSidecar.enabled }}
      initContainers:
        - name: ca-certs-updater
          image: {{ .Values.caCertsSidecar.image.repository }}:{{ .Values.caCertsSidecar.image.tag }}
          imagePullPolicy: {{ .Values.caCertsSidecar.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              # Ensure directories exist (volumes are already mounted at this point)
              mkdir -p /usr/local/share/ca-certificates /etc/ca-certificates/update.d /etc/ssl/certs 2>/dev/null || true
              # Try to use update-ca-certificates if available (from ca-certificates package)
              if command -v update-ca-certificates >/dev/null 2>&1; then
                echo "Using update-ca-certificates to generate bundle..."
                if update-ca-certificates 2>&1 && [ -f /etc/ssl/certs/ca-certificates.crt ]; then
                  echo "Certificate bundle created using update-ca-certificates"
                else
                  echo "Warning: update-ca-certificates failed, trying manual method..."
                  # Fall through to manual method
                fi
              fi
              # Manual method: create bundle directly from certificate files
              # This works even without the ca-certificates package
              if [ ! -f /etc/ssl/certs/ca-certificates.crt ]; then
                echo "Creating certificate bundle manually..."
                # Try to find certificates in common locations
                CERT_SOURCES=""
                if [ -d /usr/share/ca-certificates ]; then
                  CERT_SOURCES="/usr/share/ca-certificates"
                fi
                if [ -d /etc/ssl/certs ] && [ "$(ls -A /etc/ssl/certs/*.crt 2>/dev/null | head -1)" ]; then
                  CERT_SOURCES="$CERT_SOURCES /etc/ssl/certs"
                fi
                if [ -z "$CERT_SOURCES" ]; then
                  echo "Error: No certificate sources found"
                  echo "Trying to install ca-certificates package as last resort..."
                  if apk update >/dev/null 2>&1 && apk add --no-cache ca-certificates >/dev/null 2>&1; then
                    echo "Package installed, trying update-ca-certificates again..."
                    update-ca-certificates 2>&1 || true
                    CERT_SOURCES="/usr/share/ca-certificates"
                  else
                    echo "Error: Cannot find certificates and package installation failed"
                    echo "This might be a network/DNS issue. Please check pod network connectivity."
                    exit 1
                  fi
                fi
                # Create bundle from found certificates
                if [ -n "$CERT_SOURCES" ]; then
                  echo "Creating bundle from: $CERT_SOURCES"
                  > /etc/ssl/certs/ca-certificates.crt
                  for source in $CERT_SOURCES; do
                    if [ -d "$source" ]; then
                      find "$source" -name "*.crt" -type f -exec cat {} \; >> /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true
                    fi
                  done
                fi
              fi
              # If custom certs exist, add them to the bundle
              if [ -d "/usr/local/share/ca-certificates" ] && [ "$(ls -A /usr/local/share/ca-certificates 2>/dev/null)" ]; then
                echo "Found custom certificates, adding to bundle..."
                find /usr/local/share/ca-certificates -type f \( -name "*.crt" -o -name "*.pem" \) -exec cat {} \; >> /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true
              fi
              # Verify certificate bundle exists in the mounted volume
              if [ -f /etc/ssl/certs/ca-certificates.crt ]; then
                CERT_COUNT=$(grep -c "BEGIN CERTIFICATE" /etc/ssl/certs/ca-certificates.crt 2>/dev/null || echo "0")
                if [ "$CERT_COUNT" -gt 0 ]; then
                  echo "CA certificates initialized successfully (found $CERT_COUNT certificates)"
                  ls -lh /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true
                else
                  echo "Error: Certificate bundle exists but appears empty"
                  exit 1
                fi
              else
                echo "Error: ca-certificates.crt not found after initialization"
                echo "Debug: Listing /etc/ssl/certs/ contents:"
                ls -la /etc/ssl/certs/ 2>&1 || true
                exit 1
              fi
              # Ensure /etc/ca-certificates structure is complete
              mkdir -p /etc/ca-certificates/update.d 2>/dev/null || true
              echo "Init container completed successfully"
          volumeMounts:
            - name: ca-certs
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: etc-ca-certificates
              mountPath: /etc/ca-certificates
          {{- with .Values.caCertsSidecar.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - DAC_OVERRIDE
      {{- end }}
      volumes:
        {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmp
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        {{- end }}
        {{- if .Values.caCertsSidecar.enabled }}
        - name: ca-certs
          {{- if .Values.caCertsSidecar.configMap }}
          configMap:
            name: {{ .Values.caCertsSidecar.configMap }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: etc-ssl-certs
          emptyDir: {}
        - name: etc-ca-certificates
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}

