{{- if and .Values.gateway.enabled (or .Values.gateway.gatewayName .Values.gateway.parentRefs) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "yopass.fullname" . }}
  labels:
    {{- include "yopass.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.parentRefs }}
  parentRefs:
    {{- range .Values.gateway.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  {{- else if .Values.gateway.gatewayName }}
  parentRefs:
    - name: {{ .Values.gateway.gatewayName }}
      {{- if .Values.gateway.gatewayNamespace }}
      namespace: {{ .Values.gateway.gatewayNamespace }}
      {{- else }}
      namespace: {{ .Release.Namespace }}
      {{- end }}
  {{- end }}
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ .hostname | quote }}
    {{- end }}
  rules:
    {{- if .Values.gateway.rules }}
    {{- range .Values.gateway.rules }}
    - matches:
        {{- range .matches }}
        - path:
            {{- if .path.type }}
            type: {{ .path.type }}
            {{- else }}
            type: PathPrefix
            {{- end }}
            {{- if .path.value }}
            value: {{ .path.value | quote }}
            {{- else }}
            value: /
            {{- end }}
        {{- if .headers }}
        headers:
          {{- range .headers }}
          - type: {{ .type }}
            name: {{ .name | quote }}
            {{- if .value }}
            value: {{ .value | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if .method }}
        method: {{ .method | quote }}
        {{- end }}
        {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "yopass.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "yopass.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
{{- end }}

